#include "../interface/NtupleBranches.h"

NtupleBranches::NtupleBranches( std::map< std::string, bool>& runFlags, TTree* tree )
  : tree_( tree )
{
  branch( runFlags );
}

NtupleBranches::~NtupleBranches( void )
{
}

void NtupleBranches::branch( std::map< std::string, bool >& runFlags ){

  /*------ EVENT infos --------*/
  tree_ -> Branch("EVENT_event", &EVENT_event );
  tree_ -> Branch("EVENT_run", &EVENT_run );
  tree_ -> Branch("EVENT_lumiBlock", &EVENT_lumiBlock);


  /*------ MET Branches -----*/
  if (runFlags["doMissingEt"]){
    // MET without PF
    tree_ -> Branch("METraw_pt", &METraw_pt);
    tree_ -> Branch("METraw_phi", &METraw_phi);
    tree_ -> Branch("METraw_sumEt", &METraw_sumEt);
    tree_ -> Branch("MET_pt", &MET_pt);
    tree_ -> Branch("MET_px", &MET_px);
    tree_ -> Branch("MET_py", &MET_py);
    tree_ -> Branch("MET_phi", &MET_phi);
    tree_ -> Branch("MET_sumEt", &MET_sumEt);
    //-- PT --//
    tree_ -> Branch("MET_JetResUp_pt", &MET_JetResUp_pt);
    tree_ -> Branch("MET_JetResDown_pt", &MET_JetResDown_pt);
    tree_ -> Branch("MET_JetEnUp_pt", &MET_JetEnUp_pt);
    tree_ -> Branch("MET_JetEnDown_pt", &MET_JetEnDown_pt);
    tree_ -> Branch("MET_MuonEnUp_pt", &MET_MuonEnUp_pt);
    tree_ -> Branch("MET_MuonEnDown_pt", &MET_MuonEnDown_pt);
    tree_ -> Branch("MET_ElectronEnUp_pt", &MET_ElectronEnUp_pt);
    tree_ -> Branch("MET_ElectronEnDown_pt", &MET_ElectronEnDown_pt);
    tree_ -> Branch("MET_TauEnUp_pt", &MET_TauEnUp_pt);
    tree_ -> Branch("MET_TauEnDown_pt", &MET_TauEnDown_pt);
    tree_ -> Branch("MET_UnclusteredEnUp_pt", &MET_UnclusteredEnUp_pt);
    tree_ -> Branch("MET_UnclusteredEnDown_pt", &MET_UnclusteredEnDown_pt);
    tree_ -> Branch("MET_PhotonEnUp_pt", &MET_PhotonEnUp_pt);
    tree_ -> Branch("MET_PhotonEnDown_pt", &MET_PhotonEnDown_pt);
    tree_ -> Branch("MET_NoShift_pt", &MET_NoShift_pt);
    tree_ -> Branch("MET_METUncertaintySize_pt", &MET_METUncertaintySize_pt);
    tree_ -> Branch("MET_JetResUpSmear_pt", &MET_JetResUpSmear_pt);
    tree_ -> Branch("MET_JetResDownSmear_pt", &MET_JetResDownSmear_pt);
    tree_ -> Branch("MET_METFullUncertaintySize_pt", &MET_METFullUncertaintySize_pt);
    //--- PX --//
    tree_ -> Branch("MET_JetResUp_px", &MET_JetResUp_px);
    tree_ -> Branch("MET_JetResDown_px", &MET_JetResDown_px);
    tree_ -> Branch("MET_JetEnUp_px", &MET_JetEnUp_px);
    tree_ -> Branch("MET_JetEnDown_px", &MET_JetEnDown_px);
    tree_ -> Branch("MET_MuonEnUp_px", &MET_MuonEnUp_px);
    tree_ -> Branch("MET_MuonEnDown_px", &MET_MuonEnDown_px);
    tree_ -> Branch("MET_ElectronEnUp_px", &MET_ElectronEnUp_px);
    tree_ -> Branch("MET_ElectronEnDown_px", &MET_ElectronEnDown_px);
    tree_ -> Branch("MET_TauEnUp_px", &MET_TauEnUp_px);
    tree_ -> Branch("MET_TauEnDown_px", &MET_TauEnDown_px);
    tree_ -> Branch("MET_UnclusteredEnUp_px", &MET_UnclusteredEnUp_px);
    tree_ -> Branch("MET_UnclusteredEnDown_px", &MET_UnclusteredEnDown_px);
    tree_ -> Branch("MET_PhotonEnUp_px", &MET_PhotonEnUp_px);
    tree_ -> Branch("MET_PhotonEnDown_px", &MET_PhotonEnDown_px);
    tree_ -> Branch("MET_NoShift_px", &MET_NoShift_px);
    tree_ -> Branch("MET_METUncertaintySize_px", &MET_METUncertaintySize_px);
    tree_ -> Branch("MET_JetResUpSmear_px", &MET_JetResUpSmear_px);
    tree_ -> Branch("MET_JetResDownSmear_px", &MET_JetResDownSmear_px);
    tree_ -> Branch("MET_METFullUncertaintySize_px", &MET_METFullUncertaintySize_px);
    //-- PY --//
    tree_ -> Branch("MET_JetResUp_py", &MET_JetResUp_py);
    tree_ -> Branch("MET_JetResDown_py", &MET_JetResDown_py);
    tree_ -> Branch("MET_JetEnUp_py", &MET_JetEnUp_py);
    tree_ -> Branch("MET_JetEnDown_py", &MET_JetEnDown_py);
    tree_ -> Branch("MET_MuonEnUp_py", &MET_MuonEnUp_py);
    tree_ -> Branch("MET_MuonEnDown_py", &MET_MuonEnDown_py);
    tree_ -> Branch("MET_ElectronEnUp_py", &MET_ElectronEnUp_py);
    tree_ -> Branch("MET_ElectronEnDown_py", &MET_ElectronEnDown_py);
    tree_ -> Branch("MET_TauEnUp_py", &MET_TauEnUp_py);
    tree_ -> Branch("MET_TauEnDown_py", &MET_TauEnDown_py);
    tree_ -> Branch("MET_UnclusteredEnUp_py", &MET_UnclusteredEnUp_py);
    tree_ -> Branch("MET_UnclusteredEnDown_py", &MET_UnclusteredEnDown_py);
    tree_ -> Branch("MET_PhotonEnUp_py", &MET_PhotonEnUp_py);
    tree_ -> Branch("MET_PhotonEnDown_py", &MET_PhotonEnDown_py);
    tree_ -> Branch("MET_NoShift_py", &MET_NoShift_py);
    tree_ -> Branch("MET_METUncertaintySize_py", &MET_METUncertaintySize_py);
    tree_ -> Branch("MET_JetResUpSmear_py", &MET_JetResUpSmear_py);
    tree_ -> Branch("MET_JetResDownSmear_py", &MET_JetResDownSmear_py);
    tree_ -> Branch("MET_METFullUncertaintySize_py", &MET_METFullUncertaintySize_py);
    //-- Phi --//
    tree_ -> Branch("MET_JetResUp_phi", &MET_JetResUp_phi);
    tree_ -> Branch("MET_JetResDown_phi", &MET_JetResDown_phi);
    tree_ -> Branch("MET_JetEnUp_phi", &MET_JetEnUp_phi);
    tree_ -> Branch("MET_JetEnDown_phi", &MET_JetEnDown_phi);
    tree_ -> Branch("MET_MuonEnUp_phi", &MET_MuonEnUp_phi);
    tree_ -> Branch("MET_MuonEnDown_phi", &MET_MuonEnDown_phi);
    tree_ -> Branch("MET_ElectronEnUp_phi", &MET_ElectronEnUp_phi);
    tree_ -> Branch("MET_ElectronEnDown_phi", &MET_ElectronEnDown_phi);
    tree_ -> Branch("MET_TauEnUp_phi", &MET_TauEnUp_phi);
    tree_ -> Branch("MET_TauEnDown_phi", &MET_TauEnDown_phi);
    tree_ -> Branch("MET_UnclusteredEnUp_phi", &MET_UnclusteredEnUp_phi);
    tree_ -> Branch("MET_UnclusteredEnDown_phi", &MET_UnclusteredEnDown_phi);
    tree_ -> Branch("MET_PhotonEnUp_phi", &MET_PhotonEnUp_phi);
    tree_ -> Branch("MET_PhotonEnDown_phi", &MET_PhotonEnDown_phi);
    tree_ -> Branch("MET_NoShift_phi", &MET_NoShift_phi);
    tree_ -> Branch("MET_METUncertaintySize_phi", &MET_METUncertaintySize_phi);
    tree_ -> Branch("MET_JetResUpSmear_phi", &MET_JetResUpSmear_phi);
    tree_ -> Branch("MET_JetResDownSmear_phi", &MET_JetResDownSmear_phi);
    tree_ -> Branch("MET_METFullUncertaintySize_phi", &MET_METFullUncertaintySize_phi);
    //-- SumEt --//
    tree_ -> Branch("MET_JetResUp_sumEt", &MET_JetResUp_sumEt);
    tree_ -> Branch("MET_JetResDown_sumEt", &MET_JetResDown_sumEt);
    tree_ -> Branch("MET_JetEnUp_sumEt", &MET_JetEnUp_sumEt);
    tree_ -> Branch("MET_JetEnDown_sumEt", &MET_JetEnDown_sumEt);
    tree_ -> Branch("MET_MuonEnUp_sumEt", &MET_MuonEnUp_sumEt);
    tree_ -> Branch("MET_MuonEnDown_sumEt", &MET_MuonEnDown_sumEt);
    tree_ -> Branch("MET_ElectronEnUp_sumEt", &MET_ElectronEnUp_sumEt);
    tree_ -> Branch("MET_ElectronEnDown_sumEt", &MET_ElectronEnDown_sumEt);
    tree_ -> Branch("MET_TauEnUp_sumEt", &MET_TauEnUp_sumEt);
    tree_ -> Branch("MET_TauEnDown_sumEt", &MET_TauEnDown_sumEt);
    tree_ -> Branch("MET_UnclusteredEnUp_sumEt", &MET_UnclusteredEnUp_sumEt);
    tree_ -> Branch("MET_UnclusteredEnDown_sumEt", &MET_UnclusteredEnDown_sumEt);
    tree_ -> Branch("MET_PhotonEnUp_sumEt", &MET_PhotonEnUp_sumEt);
    tree_ -> Branch("MET_PhotonEnDown_sumEt", &MET_PhotonEnDown_sumEt);
    tree_ -> Branch("MET_NoShift_sumEt", &MET_NoShift_sumEt);
    tree_ -> Branch("MET_METUncertaintySize_sumEt", &MET_METUncertaintySize_sumEt);
    tree_ -> Branch("MET_JetResUpSmear_sumEt", &MET_JetResUpSmear_sumEt);
    tree_ -> Branch("MET_JetResDownSmear_sumEt", &MET_JetResDownSmear_sumEt);
    tree_ -> Branch("MET_METFullUncertaintySize_sumEt", &MET_METFullUncertaintySize_sumEt);
    // MET with PF
    tree_ -> Branch("METPFraw_pt", &METPFraw_pt);
    tree_ -> Branch("METPFraw_phi", &METPFraw_phi);
    tree_ -> Branch("METPFraw_sumEt", &METPFraw_sumEt);
    tree_ -> Branch("METPF_pt", &METPF_pt);
    tree_ -> Branch("METPF_px", &METPF_px);
    tree_ -> Branch("METPF_py", &METPF_py);
    tree_ -> Branch("METPF_phi", &METPF_phi);
    tree_ -> Branch("METPF_sumEt", &METPF_sumEt);
    //-- PT --//
    tree_ -> Branch("METPF_JetResUp_pt", &METPF_JetResUp_pt);
    tree_ -> Branch("METPF_JetResDown_pt", &METPF_JetResDown_pt);
    tree_ -> Branch("METPF_JetEnUp_pt", &METPF_JetEnUp_pt);
    tree_ -> Branch("METPF_JetEnDown_pt", &METPF_JetEnDown_pt);
    tree_ -> Branch("METPF_MuonEnUp_pt", &METPF_MuonEnUp_pt);
    tree_ -> Branch("METPF_MuonEnDown_pt", &METPF_MuonEnDown_pt);
    tree_ -> Branch("METPF_ElectronEnUp_pt", &METPF_ElectronEnUp_pt);
    tree_ -> Branch("METPF_ElectronEnDown_pt", &METPF_ElectronEnDown_pt);
    tree_ -> Branch("METPF_TauEnUp_pt", &METPF_TauEnUp_pt);
    tree_ -> Branch("METPF_TauEnDown_pt", &METPF_TauEnDown_pt);
    tree_ -> Branch("METPF_UnclusteredEnUp_pt", &METPF_UnclusteredEnUp_pt);
    tree_ -> Branch("METPF_UnclusteredEnDown_pt", &METPF_UnclusteredEnDown_pt);
    tree_ -> Branch("METPF_PhotonEnUp_pt", &METPF_PhotonEnUp_pt);
    tree_ -> Branch("METPF_PhotonEnDown_pt", &METPF_PhotonEnDown_pt);
    tree_ -> Branch("METPF_NoShift_pt", &METPF_NoShift_pt);
    tree_ -> Branch("METPF_METUncertaintySize_pt", &METPF_METUncertaintySize_pt);
    tree_ -> Branch("METPF_JetResUpSmear_pt", &METPF_JetResUpSmear_pt);
    tree_ -> Branch("METPF_JetResDownSmear_pt", &METPF_JetResDownSmear_pt);
    tree_ -> Branch("METPF_METFullUncertaintySize_pt", &METPF_METFullUncertaintySize_pt);
    //--- PX --//
    tree_ -> Branch("METPF_JetResUp_px", &METPF_JetResUp_px);
    tree_ -> Branch("METPF_JetResDown_px", &METPF_JetResDown_px);
    tree_ -> Branch("METPF_JetEnUp_px", &METPF_JetEnUp_px);
    tree_ -> Branch("METPF_JetEnDown_px", &METPF_JetEnDown_px);
    tree_ -> Branch("METPF_MuonEnUp_px", &METPF_MuonEnUp_px);
    tree_ -> Branch("METPF_MuonEnDown_px", &METPF_MuonEnDown_px);
    tree_ -> Branch("METPF_ElectronEnUp_px", &METPF_ElectronEnUp_px);
    tree_ -> Branch("METPF_ElectronEnDown_px", &METPF_ElectronEnDown_px);
    tree_ -> Branch("METPF_TauEnUp_px", &METPF_TauEnUp_px);
    tree_ -> Branch("METPF_TauEnDown_px", &METPF_TauEnDown_px);
    tree_ -> Branch("METPF_UnclusteredEnUp_px", &METPF_UnclusteredEnUp_px);
    tree_ -> Branch("METPF_UnclusteredEnDown_px", &METPF_UnclusteredEnDown_px);
    tree_ -> Branch("METPF_PhotonEnUp_px", &METPF_PhotonEnUp_px);
    tree_ -> Branch("METPF_PhotonEnDown_px", &METPF_PhotonEnDown_px);
    tree_ -> Branch("METPF_NoShift_px", &METPF_NoShift_px);
    tree_ -> Branch("METPF_METUncertaintySize_px", &METPF_METUncertaintySize_px);
    tree_ -> Branch("METPF_JetResUpSmear_px", &METPF_JetResUpSmear_px);
    tree_ -> Branch("METPF_JetResDownSmear_px", &METPF_JetResDownSmear_px);
    tree_ -> Branch("METPF_METFullUncertaintySize_px", &METPF_METFullUncertaintySize_px);
    //-- PY --//
    tree_ -> Branch("METPF_JetResUp_py", &METPF_JetResUp_py);
    tree_ -> Branch("METPF_JetResDown_py", &METPF_JetResDown_py);
    tree_ -> Branch("METPF_JetEnUp_py", &METPF_JetEnUp_py);
    tree_ -> Branch("METPF_JetEnDown_py", &METPF_JetEnDown_py);
    tree_ -> Branch("METPF_MuonEnUp_py", &METPF_MuonEnUp_py);
    tree_ -> Branch("METPF_MuonEnDown_py", &METPF_MuonEnDown_py);
    tree_ -> Branch("METPF_ElectronEnUp_py", &METPF_ElectronEnUp_py);
    tree_ -> Branch("METPF_ElectronEnDown_py", &METPF_ElectronEnDown_py);
    tree_ -> Branch("METPF_TauEnUp_py", &METPF_TauEnUp_py);
    tree_ -> Branch("METPF_TauEnDown_py", &METPF_TauEnDown_py);
    tree_ -> Branch("METPF_UnclusteredEnUp_py", &METPF_UnclusteredEnUp_py);
    tree_ -> Branch("METPF_UnclusteredEnDown_py", &METPF_UnclusteredEnDown_py);
    tree_ -> Branch("METPF_PhotonEnUp_py", &METPF_PhotonEnUp_py);
    tree_ -> Branch("METPF_PhotonEnDown_py", &METPF_PhotonEnDown_py);
    tree_ -> Branch("METPF_NoShift_py", &METPF_NoShift_py);
    tree_ -> Branch("METPF_METUncertaintySize_py", &METPF_METUncertaintySize_py);
    tree_ -> Branch("METPF_JetResUpSmear_py", &METPF_JetResUpSmear_py);
    tree_ -> Branch("METPF_JetResDownSmear_py", &METPF_JetResDownSmear_py);
    tree_ -> Branch("METPF_METFullUncertaintySize_py", &METPF_METFullUncertaintySize_py);
    //-- Phi --//
    tree_ -> Branch("METPF_JetResUp_phi", &METPF_JetResUp_phi);
    tree_ -> Branch("METPF_JetResDown_phi", &METPF_JetResDown_phi);
    tree_ -> Branch("METPF_JetEnUp_phi", &METPF_JetEnUp_phi);
    tree_ -> Branch("METPF_JetEnDown_phi", &METPF_JetEnDown_phi);
    tree_ -> Branch("METPF_MuonEnUp_phi", &METPF_MuonEnUp_phi);
    tree_ -> Branch("METPF_MuonEnDown_phi", &METPF_MuonEnDown_phi);
    tree_ -> Branch("METPF_ElectronEnUp_phi", &METPF_ElectronEnUp_phi);
    tree_ -> Branch("METPF_ElectronEnDown_phi", &METPF_ElectronEnDown_phi);
    tree_ -> Branch("METPF_TauEnUp_phi", &METPF_TauEnUp_phi);
    tree_ -> Branch("METPF_TauEnDown_phi", &METPF_TauEnDown_phi);
    tree_ -> Branch("METPF_UnclusteredEnUp_phi", &METPF_UnclusteredEnUp_phi);
    tree_ -> Branch("METPF_UnclusteredEnDown_phi", &METPF_UnclusteredEnDown_phi);
    tree_ -> Branch("METPF_PhotonEnUp_phi", &METPF_PhotonEnUp_phi);
    tree_ -> Branch("METPF_PhotonEnDown_phi", &METPF_PhotonEnDown_phi);
    tree_ -> Branch("METPF_NoShift_phi", &METPF_NoShift_phi);
    tree_ -> Branch("METPF_METUncertaintySize_phi", &METPF_METUncertaintySize_phi);
    tree_ -> Branch("METPF_JetResUpSmear_phi", &METPF_JetResUpSmear_phi);
    tree_ -> Branch("METPF_JetResDownSmear_phi", &METPF_JetResDownSmear_phi);
    tree_ -> Branch("METPF_METFullUncertaintySize_phi", &METPF_METFullUncertaintySize_phi);
    //-- SumEt --//
    tree_ -> Branch("METPF_JetResUp_sumEt", &METPF_JetResUp_sumEt);
    tree_ -> Branch("METPF_JetResDown_sumEt", &METPF_JetResDown_sumEt);
    tree_ -> Branch("METPF_JetEnUp_sumEt", &METPF_JetEnUp_sumEt);
    tree_ -> Branch("METPF_JetEnDown_sumEt", &METPF_JetEnDown_sumEt);
    tree_ -> Branch("METPF_MuonEnUp_sumEt", &METPF_MuonEnUp_sumEt);
    tree_ -> Branch("METPF_MuonEnDown_sumEt", &METPF_MuonEnDown_sumEt);
    tree_ -> Branch("METPF_ElectronEnUp_sumEt", &METPF_ElectronEnUp_sumEt);
    tree_ -> Branch("METPF_ElectronEnDown_sumEt", &METPF_ElectronEnDown_sumEt);
    tree_ -> Branch("METPF_TauEnUp_sumEt", &METPF_TauEnUp_sumEt);
    tree_ -> Branch("METPF_TauEnDown_sumEt", &METPF_TauEnDown_sumEt);
    tree_ -> Branch("METPF_UnclusteredEnUp_sumEt", &METPF_UnclusteredEnUp_sumEt);
    tree_ -> Branch("METPF_UnclusteredEnDown_sumEt", &METPF_UnclusteredEnDown_sumEt);
    tree_ -> Branch("METPF_PhotonEnUp_sumEt", &METPF_PhotonEnUp_sumEt);
    tree_ -> Branch("METPF_PhotonEnDown_sumEt", &METPF_PhotonEnDown_sumEt);
    tree_ -> Branch("METPF_NoShift_sumEt", &METPF_NoShift_sumEt);
    tree_ -> Branch("METPF_METUncertaintySize_sumEt", &METPF_METUncertaintySize_sumEt);
    tree_ -> Branch("METPF_JetResUpSmear_sumEt", &METPF_JetResUpSmear_sumEt);
    tree_ -> Branch("METPF_JetResDownSmear_sumEt", &METPF_JetResDownSmear_sumEt);
    tree_ -> Branch("METPF_METFullUncertaintySize_sumEt", &METPF_METFullUncertaintySize_sumEt);
    // MET Puppi without PF
    tree_ -> Branch("METPuppiraw_pt", &METPuppiraw_pt);
    tree_ -> Branch("METPuppiraw_phi", &METPuppiraw_phi);
    tree_ -> Branch("METPuppiraw_sumEt", &METPuppiraw_sumEt);
    tree_ -> Branch("METPuppi_pt", &METPuppi_pt);
    tree_ -> Branch("METPuppi_px", &METPuppi_px);
    tree_ -> Branch("METPuppi_py", &METPuppi_py);
    tree_ -> Branch("METPuppi_phi", &METPuppi_phi);
    tree_ -> Branch("METPuppi_sumEt", &METPuppi_sumEt);
    //-- PT --//
    tree_ -> Branch("METPuppi_JetResUp_pt", &METPuppi_JetResUp_pt);
    tree_ -> Branch("METPuppi_JetResDown_pt", &METPuppi_JetResDown_pt);
    tree_ -> Branch("METPuppi_JetEnUp_pt", &METPuppi_JetEnUp_pt);
    tree_ -> Branch("METPuppi_JetEnDown_pt", &METPuppi_JetEnDown_pt);
    tree_ -> Branch("METPuppi_MuonEnUp_pt", &METPuppi_MuonEnUp_pt);
    tree_ -> Branch("METPuppi_MuonEnDown_pt", &METPuppi_MuonEnDown_pt);
    tree_ -> Branch("METPuppi_ElectronEnUp_pt", &METPuppi_ElectronEnUp_pt);
    tree_ -> Branch("METPuppi_ElectronEnDown_pt", &METPuppi_ElectronEnDown_pt);
    tree_ -> Branch("METPuppi_TauEnUp_pt", &METPuppi_TauEnUp_pt);
    tree_ -> Branch("METPuppi_TauEnDown_pt", &METPuppi_TauEnDown_pt);
    tree_ -> Branch("METPuppi_UnclusteredEnUp_pt", &METPuppi_UnclusteredEnUp_pt);
    tree_ -> Branch("METPuppi_UnclusteredEnDown_pt", &METPuppi_UnclusteredEnDown_pt);
    tree_ -> Branch("METPuppi_PhotonEnUp_pt", &METPuppi_PhotonEnUp_pt);
    tree_ -> Branch("METPuppi_PhotonEnDown_pt", &METPuppi_PhotonEnDown_pt);
    tree_ -> Branch("METPuppi_NoShift_pt", &METPuppi_NoShift_pt);
    tree_ -> Branch("METPuppi_METUncertaintySize_pt", &METPuppi_METUncertaintySize_pt);
    tree_ -> Branch("METPuppi_JetResUpSmear_pt", &METPuppi_JetResUpSmear_pt);
    tree_ -> Branch("METPuppi_JetResDownSmear_pt", &METPuppi_JetResDownSmear_pt);
    tree_ -> Branch("METPuppi_METFullUncertaintySize_pt", &METPuppi_METFullUncertaintySize_pt);
    //--- PX --//
    tree_ -> Branch("METPuppi_JetResUp_px", &METPuppi_JetResUp_px);
    tree_ -> Branch("METPuppi_JetResDown_px", &METPuppi_JetResDown_px);
    tree_ -> Branch("METPuppi_JetEnUp_px", &METPuppi_JetEnUp_px);
    tree_ -> Branch("METPuppi_JetEnDown_px", &METPuppi_JetEnDown_px);
    tree_ -> Branch("METPuppi_MuonEnUp_px", &METPuppi_MuonEnUp_px);
    tree_ -> Branch("METPuppi_MuonEnDown_px", &METPuppi_MuonEnDown_px);
    tree_ -> Branch("METPuppi_ElectronEnUp_px", &METPuppi_ElectronEnUp_px);
    tree_ -> Branch("METPuppi_ElectronEnDown_px", &METPuppi_ElectronEnDown_px);
    tree_ -> Branch("METPuppi_TauEnUp_px", &METPuppi_TauEnUp_px);
    tree_ -> Branch("METPuppi_TauEnDown_px", &METPuppi_TauEnDown_px);
    tree_ -> Branch("METPuppi_UnclusteredEnUp_px", &METPuppi_UnclusteredEnUp_px);
    tree_ -> Branch("METPuppi_UnclusteredEnDown_px", &METPuppi_UnclusteredEnDown_px);
    tree_ -> Branch("METPuppi_PhotonEnUp_px", &METPuppi_PhotonEnUp_px);
    tree_ -> Branch("METPuppi_PhotonEnDown_px", &METPuppi_PhotonEnDown_px);
    tree_ -> Branch("METPuppi_NoShift_px", &METPuppi_NoShift_px);
    tree_ -> Branch("METPuppi_METUncertaintySize_px", &METPuppi_METUncertaintySize_px);
    tree_ -> Branch("METPuppi_JetResUpSmear_px", &METPuppi_JetResUpSmear_px);
    tree_ -> Branch("METPuppi_JetResDownSmear_px", &METPuppi_JetResDownSmear_px);
    tree_ -> Branch("METPuppi_METFullUncertaintySize_px", &METPuppi_METFullUncertaintySize_px);
    //-- PY --//
    tree_ -> Branch("METPuppi_JetResUp_py", &METPuppi_JetResUp_py);
    tree_ -> Branch("METPuppi_JetResDown_py", &METPuppi_JetResDown_py);
    tree_ -> Branch("METPuppi_JetEnUp_py", &METPuppi_JetEnUp_py);
    tree_ -> Branch("METPuppi_JetEnDown_py", &METPuppi_JetEnDown_py);
    tree_ -> Branch("METPuppi_MuonEnUp_py", &METPuppi_MuonEnUp_py);
    tree_ -> Branch("METPuppi_MuonEnDown_py", &METPuppi_MuonEnDown_py);
    tree_ -> Branch("METPuppi_ElectronEnUp_py", &METPuppi_ElectronEnUp_py);
    tree_ -> Branch("METPuppi_ElectronEnDown_py", &METPuppi_ElectronEnDown_py);
    tree_ -> Branch("METPuppi_TauEnUp_py", &METPuppi_TauEnUp_py);
    tree_ -> Branch("METPuppi_TauEnDown_py", &METPuppi_TauEnDown_py);
    tree_ -> Branch("METPuppi_UnclusteredEnUp_py", &METPuppi_UnclusteredEnUp_py);
    tree_ -> Branch("METPuppi_UnclusteredEnDown_py", &METPuppi_UnclusteredEnDown_py);
    tree_ -> Branch("METPuppi_PhotonEnUp_py", &METPuppi_PhotonEnUp_py);
    tree_ -> Branch("METPuppi_PhotonEnDown_py", &METPuppi_PhotonEnDown_py);
    tree_ -> Branch("METPuppi_NoShift_py", &METPuppi_NoShift_py);
    tree_ -> Branch("METPuppi_METUncertaintySize_py", &METPuppi_METUncertaintySize_py);
    tree_ -> Branch("METPuppi_JetResUpSmear_py", &METPuppi_JetResUpSmear_py);
    tree_ -> Branch("METPuppi_JetResDownSmear_py", &METPuppi_JetResDownSmear_py);
    tree_ -> Branch("METPuppi_METFullUncertaintySize_py", &METPuppi_METPuppiFullUncertaintySize_py);
    //-- Phi --//
    tree_ -> Branch("METPuppi_JetResUp_phi", &METPuppi_JetResUp_phi);
    tree_ -> Branch("METPuppi_JetResDown_phi", &METPuppi_JetResDown_phi);
    tree_ -> Branch("METPuppi_JetEnUp_phi", &METPuppi_JetEnUp_phi);
    tree_ -> Branch("METPuppi_JetEnDown_phi", &METPuppi_JetEnDown_phi);
    tree_ -> Branch("METPuppi_MuonEnUp_phi", &METPuppi_MuonEnUp_phi);
    tree_ -> Branch("METPuppi_MuonEnDown_phi", &METPuppi_MuonEnDown_phi);
    tree_ -> Branch("METPuppi_ElectronEnUp_phi", &METPuppi_ElectronEnUp_phi);
    tree_ -> Branch("METPuppi_ElectronEnDown_phi", &METPuppi_ElectronEnDown_phi);
    tree_ -> Branch("METPuppi_TauEnUp_phi", &METPuppi_TauEnUp_phi);
    tree_ -> Branch("METPuppi_TauEnDown_phi", &METPuppi_TauEnDown_phi);
    tree_ -> Branch("METPuppi_UnclusteredEnUp_phi", &METPuppi_UnclusteredEnUp_phi);
    tree_ -> Branch("METPuppi_UnclusteredEnDown_phi", &METPuppi_UnclusteredEnDown_phi);
    tree_ -> Branch("METPuppi_PhotonEnUp_phi", &METPuppi_PhotonEnUp_phi);
    tree_ -> Branch("METPuppi_PhotonEnDown_phi", &METPuppi_PhotonEnDown_phi);
    tree_ -> Branch("METPuppi_NoShift_phi", &METPuppi_NoShift_phi);
    tree_ -> Branch("METPuppi_METUncertaintySize_phi", &METPuppi_METUncertaintySize_phi);
    tree_ -> Branch("METPuppi_JetResUpSmear_phi", &METPuppi_JetResUpSmear_phi);
    tree_ -> Branch("METPuppi_JetResDownSmear_phi", &METPuppi_JetResDownSmear_phi);
    tree_ -> Branch("METPuppi_METFullUncertaintySize_phi", &METPuppi_METFullUncertaintySize_phi);
    //-- SumEt --//
    tree_ -> Branch("METPuppi_JetResUp_sumEt", &METPuppi_JetResUp_sumEt);
    tree_ -> Branch("METPuppi_JetResDown_sumEt", &METPuppi_JetResDown_sumEt);
    tree_ -> Branch("METPuppi_JetEnUp_sumEt", &METPuppi_JetEnUp_sumEt);
    tree_ -> Branch("METPuppi_JetEnDown_sumEt", &METPuppi_JetEnDown_sumEt);
    tree_ -> Branch("METPuppi_MuonEnUp_sumEt", &METPuppi_MuonEnUp_sumEt);
    tree_ -> Branch("METPuppi_MuonEnDown_sumEt", &METPuppi_MuonEnDown_sumEt);
    tree_ -> Branch("METPuppi_ElectronEnUp_sumEt", &METPuppi_ElectronEnUp_sumEt);
    tree_ -> Branch("METPuppi_ElectronEnDown_sumEt", &METPuppi_ElectronEnDown_sumEt);
    tree_ -> Branch("METPuppi_TauEnUp_sumEt", &METPuppi_TauEnUp_sumEt);
    tree_ -> Branch("METPuppi_TauEnDown_sumEt", &METPuppi_TauEnDown_sumEt);
    tree_ -> Branch("METPuppi_UnclusteredEnUp_sumEt", &METPuppi_UnclusteredEnUp_sumEt);
    tree_ -> Branch("METPuppi_UnclusteredEnDown_sumEt", &METPuppi_UnclusteredEnDown_sumEt);
    tree_ -> Branch("METPuppi_PhotonEnUp_sumEt", &METPuppi_PhotonEnUp_sumEt);
    tree_ -> Branch("METPuppi_PhotonEnDown_sumEt", &METPuppi_PhotonEnDown_sumEt);
    tree_ -> Branch("METPuppi_NoShift_sumEt", &METPuppi_NoShift_sumEt);
    tree_ -> Branch("METPuppi_METUncertaintySize_sumEt", &METPuppi_METUncertaintySize_sumEt);
    tree_ -> Branch("METPuppi_JetResUpSmear_sumEt", &METPuppi_JetResUpSmear_sumEt);
    tree_ -> Branch("METPuppi_JetResDownSmear_sumEt", &METPuppi_JetResDownSmear_sumEt);
    tree_ -> Branch("METPuppi_METFullUncertaintySize_sumEt", &METPuppi_METFullUncertaintySize_sumEt);
    // MET Puppi with PF
    tree_ -> Branch("METPuppiPFraw_pt", &METPuppiPFraw_pt);
    tree_ -> Branch("METPuppiPFraw_phi", &METPuppiPFraw_phi);
    tree_ -> Branch("METPuppiPFraw_sumEt", &METPuppiPFraw_sumEt);
    tree_ -> Branch("METPuppiPF_pt", &METPuppiPF_pt);
    tree_ -> Branch("METPuppiPF_px", &METPuppiPF_px);
    tree_ -> Branch("METPuppiPF_py", &METPuppiPF_py);
    tree_ -> Branch("METPuppiPF_phi", &METPuppiPF_phi);
    tree_ -> Branch("METPuppiPF_sumEt", &METPuppiPF_sumEt);
    //-- PT --//
    tree_ -> Branch("METPuppiPF_JetResUp_pt", &METPuppiPF_JetResUp_pt);
    tree_ -> Branch("METPuppiPF_JetResDown_pt", &METPuppiPF_JetResDown_pt);
    tree_ -> Branch("METPuppiPF_JetEnUp_pt", &METPuppiPF_JetEnUp_pt);
    tree_ -> Branch("METPuppiPF_JetEnDown_pt", &METPuppiPF_JetEnDown_pt);
    tree_ -> Branch("METPuppiPF_MuonEnUp_pt", &METPuppiPF_MuonEnUp_pt);
    tree_ -> Branch("METPuppiPF_MuonEnDown_pt", &METPuppiPF_MuonEnDown_pt);
    tree_ -> Branch("METPuppiPF_ElectronEnUp_pt", &METPuppiPF_ElectronEnUp_pt);
    tree_ -> Branch("METPuppiPF_ElectronEnDown_pt", &METPuppiPF_ElectronEnDown_pt);
    tree_ -> Branch("METPuppiPF_TauEnUp_pt", &METPuppiPF_TauEnUp_pt);
    tree_ -> Branch("METPuppiPF_TauEnDown_pt", &METPuppiPF_TauEnDown_pt);
    tree_ -> Branch("METPuppiPF_UnclusteredEnUp_pt", &METPuppiPF_UnclusteredEnUp_pt);
    tree_ -> Branch("METPuppiPF_UnclusteredEnDown_pt", &METPuppiPF_UnclusteredEnDown_pt);
    tree_ -> Branch("METPuppiPF_PhotonEnUp_pt", &METPuppiPF_PhotonEnUp_pt);
    tree_ -> Branch("METPuppiPF_PhotonEnDown_pt", &METPuppiPF_PhotonEnDown_pt);
    tree_ -> Branch("METPuppiPF_NoShift_pt", &METPuppiPF_NoShift_pt);
    tree_ -> Branch("METPuppiPF_METUncertaintySize_pt", &METPuppiPF_METUncertaintySize_pt);
    tree_ -> Branch("METPuppiPF_JetResUpSmear_pt", &METPuppiPF_JetResUpSmear_pt);
    tree_ -> Branch("METPuppiPF_JetResDownSmear_pt", &METPuppiPF_JetResDownSmear_pt);
    tree_ -> Branch("METPuppiPF_METFullUncertaintySize_pt", &METPuppiPF_METFullUncertaintySize_pt);
    //--- PX --//
    tree_ -> Branch("METPuppiPF_JetResUp_px", &METPuppiPF_JetResUp_px);
    tree_ -> Branch("METPuppiPF_JetResDown_px", &METPuppiPF_JetResDown_px);
    tree_ -> Branch("METPuppiPF_JetEnUp_px", &METPuppiPF_JetEnUp_px);
    tree_ -> Branch("METPuppiPF_JetEnDown_px", &METPuppiPF_JetEnDown_px);
    tree_ -> Branch("METPuppiPF_MuonEnUp_px", &METPuppiPF_MuonEnUp_px);
    tree_ -> Branch("METPuppiPF_MuonEnDown_px", &METPuppiPF_MuonEnDown_px);
    tree_ -> Branch("METPuppiPF_ElectronEnUp_px", &METPuppiPF_ElectronEnUp_px);
    tree_ -> Branch("METPuppiPF_ElectronEnDown_px", &METPuppiPF_ElectronEnDown_px);
    tree_ -> Branch("METPuppiPF_TauEnUp_px", &METPuppiPF_TauEnUp_px);
    tree_ -> Branch("METPuppiPF_TauEnDown_px", &METPuppiPF_TauEnDown_px);
    tree_ -> Branch("METPuppiPF_UnclusteredEnUp_px", &METPuppiPF_UnclusteredEnUp_px);
    tree_ -> Branch("METPuppiPF_UnclusteredEnDown_px", &METPuppiPF_UnclusteredEnDown_px);
    tree_ -> Branch("METPuppiPF_PhotonEnUp_px", &METPuppiPF_PhotonEnUp_px);
    tree_ -> Branch("METPuppiPF_PhotonEnDown_px", &METPuppiPF_PhotonEnDown_px);
    tree_ -> Branch("METPuppiPF_NoShift_px", &METPuppiPF_NoShift_px);
    tree_ -> Branch("METPuppiPF_METUncertaintySize_px", &METPuppiPF_METUncertaintySize_px);
    tree_ -> Branch("METPuppiPF_JetResUpSmear_px", &METPuppiPF_JetResUpSmear_px);
    tree_ -> Branch("METPuppiPF_JetResDownSmear_px", &METPuppiPF_JetResDownSmear_px);
    tree_ -> Branch("METPuppiPF_METFullUncertaintySize_px", &METPuppiPF_METFullUncertaintySize_px);
    //-- PY --//
    tree_ -> Branch("METPuppiPF_JetResUp_py", &METPuppiPF_JetResUp_py);
    tree_ -> Branch("METPuppiPF_JetResDown_py", &METPuppiPF_JetResDown_py);
    tree_ -> Branch("METPuppiPF_JetEnUp_py", &METPuppiPF_JetEnUp_py);
    tree_ -> Branch("METPuppiPF_JetEnDown_py", &METPuppiPF_JetEnDown_py);
    tree_ -> Branch("METPuppiPF_MuonEnUp_py", &METPuppiPF_MuonEnUp_py);
    tree_ -> Branch("METPuppiPF_MuonEnDown_py", &METPuppiPF_MuonEnDown_py);
    tree_ -> Branch("METPuppiPF_ElectronEnUp_py", &METPuppiPF_ElectronEnUp_py);
    tree_ -> Branch("METPuppiPF_ElectronEnDown_py", &METPuppiPF_ElectronEnDown_py);
    tree_ -> Branch("METPuppiPF_TauEnUp_py", &METPuppiPF_TauEnUp_py);
    tree_ -> Branch("METPuppiPF_TauEnDown_py", &METPuppiPF_TauEnDown_py);
    tree_ -> Branch("METPuppiPF_UnclusteredEnUp_py", &METPuppiPF_UnclusteredEnUp_py);
    tree_ -> Branch("METPuppiPF_UnclusteredEnDown_py", &METPuppiPF_UnclusteredEnDown_py);
    tree_ -> Branch("METPuppiPF_PhotonEnUp_py", &METPuppiPF_PhotonEnUp_py);
    tree_ -> Branch("METPuppiPF_PhotonEnDown_py", &METPuppiPF_PhotonEnDown_py);
    tree_ -> Branch("METPuppiPF_NoShift_py", &METPuppiPF_NoShift_py);
    tree_ -> Branch("METPuppiPF_METUncertaintySize_py", &METPuppiPF_METUncertaintySize_py);
    tree_ -> Branch("METPuppiPF_JetResUpSmear_py", &METPuppiPF_JetResUpSmear_py);
    tree_ -> Branch("METPuppiPF_JetResDownSmear_py", &METPuppiPF_JetResDownSmear_py);
    tree_ -> Branch("METPuppiPF_METFullUncertaintySize_py", &METPuppiPF_METFullUncertaintySize_py);
    //-- Phi --//
    tree_ -> Branch("METPuppiPF_JetResUp_phi", &METPuppiPF_JetResUp_phi);
    tree_ -> Branch("METPuppiPF_JetResDown_phi", &METPuppiPF_JetResDown_phi);
    tree_ -> Branch("METPuppiPF_JetEnUp_phi", &METPuppiPF_JetEnUp_phi);
    tree_ -> Branch("METPuppiPF_JetEnDown_phi", &METPuppiPF_JetEnDown_phi);
    tree_ -> Branch("METPuppiPF_MuonEnUp_phi", &METPuppiPF_MuonEnUp_phi);
    tree_ -> Branch("METPuppiPF_MuonEnDown_phi", &METPuppiPF_MuonEnDown_phi);
    tree_ -> Branch("METPuppiPF_ElectronEnUp_phi", &METPuppiPF_ElectronEnUp_phi);
    tree_ -> Branch("METPuppiPF_ElectronEnDown_phi", &METPuppiPF_ElectronEnDown_phi);
    tree_ -> Branch("METPuppiPF_TauEnUp_phi", &METPuppiPF_TauEnUp_phi);
    tree_ -> Branch("METPuppiPF_TauEnDown_phi", &METPuppiPF_TauEnDown_phi);
    tree_ -> Branch("METPuppiPF_UnclusteredEnUp_phi", &METPuppiPF_UnclusteredEnUp_phi);
    tree_ -> Branch("METPuppiPF_UnclusteredEnDown_phi", &METPuppiPF_UnclusteredEnDown_phi);
    tree_ -> Branch("METPuppiPF_PhotonEnUp_phi", &METPuppiPF_PhotonEnUp_phi);
    tree_ -> Branch("METPuppiPF_PhotonEnDown_phi", &METPuppiPF_PhotonEnDown_phi);
    tree_ -> Branch("METPuppiPF_NoShift_phi", &METPuppiPF_NoShift_phi);
    tree_ -> Branch("METPuppiPF_METUncertaintySize_phi", &METPuppiPF_METUncertaintySize_phi);
    tree_ -> Branch("METPuppiPF_JetResUpSmear_phi", &METPuppiPF_JetResUpSmear_phi);
    tree_ -> Branch("METPuppiPF_JetResDownSmear_phi", &METPuppiPF_JetResDownSmear_phi);
    tree_ -> Branch("METPuppiPF_METFullUncertaintySize_phi", &METPuppiPF_METFullUncertaintySize_phi);
    //-- SumEt --//
    tree_ -> Branch("METPuppiPF_JetResUp_sumEt", &METPuppiPF_JetResUp_sumEt);
    tree_ -> Branch("METPuppiPF_JetResDown_sumEt", &METPuppiPF_JetResDown_sumEt);
    tree_ -> Branch("METPuppiPF_JetEnUp_sumEt", &METPuppiPF_JetEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_JetEnDown_sumEt", &METPuppiPF_JetEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_MuonEnUp_sumEt", &METPuppiPF_MuonEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_MuonEnDown_sumEt", &METPuppiPF_MuonEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_ElectronEnUp_sumEt", &METPuppiPF_ElectronEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_ElectronEnDown_sumEt", &METPuppiPF_ElectronEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_TauEnUp_sumEt", &METPuppiPF_TauEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_TauEnDown_sumEt", &METPuppiPF_TauEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_UnclusteredEnUp_sumEt", &METPuppiPF_UnclusteredEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_UnclusteredEnDown_sumEt", &METPuppiPF_UnclusteredEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_PhotonEnUp_sumEt", &METPuppiPF_PhotonEnUp_sumEt);
    tree_ -> Branch("METPuppiPF_PhotonEnDown_sumEt", &METPuppiPF_PhotonEnDown_sumEt);
    tree_ -> Branch("METPuppiPF_NoShift_sumEt", &METPuppiPF_NoShift_sumEt);
    tree_ -> Branch("METPuppiPF_METUncertaintySize_sumEt", &METPuppiPF_METUncertaintySize_sumEt);
    tree_ -> Branch("METPuppiPF_JetResUpSmear_sumEt", &METPuppiPF_JetResUpSmear_sumEt);
    tree_ -> Branch("METPuppiPF_JetResDownSmear_sumEt", &METPuppiPF_JetResDownSmear_sumEt);
    tree_ -> Branch("METPuppiPF_METFullUncertaintySize_sumEt", &METPuppiPF_METFullUncertaintySize_sumEt);
    
  }
}

void NtupleBranches::reset( void ){

  //------ EVENT infos -------//
  EVENT_event     = 0;
  EVENT_run       = 0;
  EVENT_lumiBlock = 0;


  //--- MET ---//
  // MET Modified without PF
   METraw_pt.clear();
   METraw_phi.clear();
   METraw_sumEt.clear();
   MET_pt.clear();
   MET_px.clear();
   MET_py.clear();
   MET_phi.clear();
   MET_sumEt.clear();
  //-- PT --//
   MET_JetResUp_pt.clear();
   MET_JetResDown_pt.clear();
   MET_JetEnUp_pt.clear();
   MET_JetEnDown_pt.clear();
   MET_MuonEnUp_pt.clear();
   MET_MuonEnDown_pt.clear();
   MET_ElectronEnUp_pt.clear();
   MET_ElectronEnDown_pt.clear();
   MET_TauEnUp_pt.clear();
   MET_TauEnDown_pt.clear();
   MET_UnclusteredEnUp_pt.clear();
   MET_UnclusteredEnDown_pt.clear();
   MET_PhotonEnUp_pt.clear();
   MET_PhotonEnDown_pt.clear();
   MET_NoShift_pt.clear();
   MET_METUncertaintySize_pt.clear();
   MET_JetResUpSmear_pt.clear();
   MET_JetResDownSmear_pt.clear();
   MET_METFullUncertaintySize_pt.clear();
  //-- PX --/
   MET_JetResUp_px.clear();
   MET_JetResDown_px.clear();
   MET_JetEnUp_px.clear();
   MET_JetEnDown_px.clear();
   MET_MuonEnUp_px.clear();
   MET_MuonEnDown_px.clear();
   MET_ElectronEnUp_px.clear();
   MET_ElectronEnDown_px.clear();
   MET_TauEnUp_px.clear();
   MET_TauEnDown_px.clear();
   MET_UnclusteredEnUp_px.clear();
   MET_UnclusteredEnDown_px.clear();
   MET_PhotonEnUp_px.clear();
   MET_PhotonEnDown_px.clear();
   MET_NoShift_px.clear();
   MET_METUncertaintySize_px.clear();
   MET_JetResUpSmear_px.clear();
   MET_JetResDownSmear_px.clear();
   MET_METFullUncertaintySize_px.clear();
  //-- PY --/
   MET_JetResUp_py.clear();
   MET_JetResDown_py.clear();
   MET_JetEnUp_py.clear();
   MET_JetEnDown_py.clear();
   MET_MuonEnUp_py.clear();
   MET_MuonEnDown_py.clear();
   MET_ElectronEnUp_py.clear();
   MET_ElectronEnDown_py.clear();
   MET_TauEnUp_py.clear();
   MET_TauEnDown_py.clear();
   MET_UnclusteredEnUp_py.clear();
   MET_UnclusteredEnDown_py.clear();
   MET_PhotonEnUp_py.clear();
   MET_PhotonEnDown_py.clear();
   MET_NoShift_py.clear();
   MET_METUncertaintySize_py.clear();
   MET_JetResUpSmear_py.clear();
   MET_JetResDownSmear_py.clear();
   MET_METFullUncertaintySize_py.clear();
  //-- PHI ---/
   MET_JetResUp_phi.clear();
   MET_JetResDown_phi.clear();
   MET_JetEnUp_phi.clear();
   MET_JetEnDown_phi.clear();
   MET_MuonEnUp_phi.clear();
   MET_MuonEnDown_phi.clear();
   MET_ElectronEnUp_phi.clear();
   MET_ElectronEnDown_phi.clear();
   MET_TauEnUp_phi.clear();
   MET_TauEnDown_phi.clear();
   MET_UnclusteredEnUp_phi.clear();
   MET_UnclusteredEnDown_phi.clear();
   MET_PhotonEnUp_phi.clear();
   MET_PhotonEnDown_phi.clear();
   MET_NoShift_phi.clear();
   MET_METUncertaintySize_phi.clear();
   MET_JetResUpSmear_phi.clear();
   MET_JetResDownSmear_phi.clear();
   MET_METFullUncertaintySize_phi.clear();
  //-- SumET --//
   MET_JetResUp_sumEt.clear();
   MET_JetResDown_sumEt.clear();
   MET_JetEnUp_sumEt.clear();
   MET_JetEnDown_sumEt.clear();
   MET_MuonEnUp_sumEt.clear();
   MET_MuonEnDown_sumEt.clear();
   MET_ElectronEnUp_sumEt.clear();
   MET_ElectronEnDown_sumEt.clear();
   MET_TauEnUp_sumEt.clear();
   MET_TauEnDown_sumEt.clear();
   MET_UnclusteredEnUp_sumEt.clear();
   MET_UnclusteredEnDown_sumEt.clear();
   MET_PhotonEnUp_sumEt.clear();
   MET_PhotonEnDown_sumEt.clear();
   MET_NoShift_sumEt.clear();
   MET_METUncertaintySize_sumEt.clear();
   MET_JetResUpSmear_sumEt.clear();
   MET_JetResDownSmear_sumEt.clear();
   MET_METFullUncertaintySize_sumEt.clear();
  //-------------------------------------------------------
  // MET Modified with PF
   METPFraw_pt.clear();
   METPFraw_phi.clear();
   METPFraw_sumEt.clear();
   METPF_pt.clear();
   METPF_px.clear();
   METPF_py.clear();
   METPF_phi.clear();
   METPF_sumEt.clear();
  //-- PT --/
   METPF_JetResUp_pt.clear();
   METPF_JetResDown_pt.clear();
   METPF_JetEnUp_pt.clear();
   METPF_JetEnDown_pt.clear();
   METPF_MuonEnUp_pt.clear();
   METPF_MuonEnDown_pt.clear();
   METPF_ElectronEnUp_pt.clear();
   METPF_ElectronEnDown_pt.clear();
   METPF_TauEnUp_pt.clear();
   METPF_TauEnDown_pt.clear();
   METPF_UnclusteredEnUp_pt.clear();
   METPF_UnclusteredEnDown_pt.clear();
   METPF_PhotonEnUp_pt.clear();
   METPF_PhotonEnDown_pt.clear();
   METPF_NoShift_pt.clear();
   METPF_METUncertaintySize_pt.clear();
   METPF_JetResUpSmear_pt.clear();
   METPF_JetResDownSmear_pt.clear();
   METPF_METFullUncertaintySize_pt.clear();
  //-- PX --//
   METPF_JetResUp_px.clear();
   METPF_JetResDown_px.clear();
   METPF_JetEnUp_px.clear();
   METPF_JetEnDown_px.clear();
   METPF_MuonEnUp_px.clear();
   METPF_MuonEnDown_px.clear();
   METPF_ElectronEnUp_px.clear();
   METPF_ElectronEnDown_px.clear();
   METPF_TauEnUp_px.clear();
   METPF_TauEnDown_px.clear();
   METPF_UnclusteredEnUp_px.clear();
   METPF_UnclusteredEnDown_px.clear();
   METPF_PhotonEnUp_px.clear();
   METPF_PhotonEnDown_px.clear();
   METPF_NoShift_px.clear();
   METPF_METUncertaintySize_px.clear();
   METPF_JetResUpSmear_px.clear();
   METPF_JetResDownSmear_px.clear();
   METPF_METFullUncertaintySize_px.clear();
  //-- PY --/
   METPF_JetResUp_py.clear();
   METPF_JetResDown_py.clear();
   METPF_JetEnUp_py.clear();
   METPF_JetEnDown_py.clear();
   METPF_MuonEnUp_py.clear();
   METPF_MuonEnDown_py.clear();
   METPF_ElectronEnUp_py.clear();
   METPF_ElectronEnDown_py.clear();
   METPF_TauEnUp_py.clear();
   METPF_TauEnDown_py.clear();
   METPF_UnclusteredEnUp_py.clear();
   METPF_UnclusteredEnDown_py.clear();
   METPF_PhotonEnUp_py.clear();
   METPF_PhotonEnDown_py.clear();
   METPF_NoShift_py.clear();
   METPF_METUncertaintySize_py.clear();
   METPF_JetResUpSmear_py.clear();
   METPF_JetResDownSmear_py.clear();
   METPF_METFullUncertaintySize_py.clear();
  //-- PHI --//
   METPF_JetResUp_phi.clear();
   METPF_JetResDown_phi.clear();
   METPF_JetEnUp_phi.clear();
   METPF_JetEnDown_phi.clear();
   METPF_MuonEnUp_phi.clear();
   METPF_MuonEnDown_phi.clear();
   METPF_ElectronEnUp_phi.clear();
   METPF_ElectronEnDown_phi.clear();
   METPF_TauEnUp_phi.clear();
   METPF_TauEnDown_phi.clear();
   METPF_UnclusteredEnUp_phi.clear();
   METPF_UnclusteredEnDown_phi.clear();
   METPF_PhotonEnUp_phi.clear();
   METPF_PhotonEnDown_phi.clear();
   METPF_NoShift_phi.clear();
   METPF_METUncertaintySize_phi.clear();
   METPF_JetResUpSmear_phi.clear();
   METPF_JetResDownSmear_phi.clear();
   METPF_METFullUncertaintySize_phi.clear();
  //-- SumEt --//
   METPF_JetResUp_sumEt.clear();
   METPF_JetResDown_sumEt.clear();
   METPF_JetEnUp_sumEt.clear();
   METPF_JetEnDown_sumEt.clear();
   METPF_MuonEnUp_sumEt.clear();
   METPF_MuonEnDown_sumEt.clear();
   METPF_ElectronEnUp_sumEt.clear();
   METPF_ElectronEnDown_sumEt.clear();
   METPF_TauEnUp_sumEt.clear();
   METPF_TauEnDown_sumEt.clear();
   METPF_UnclusteredEnUp_sumEt.clear();
   METPF_UnclusteredEnDown_sumEt.clear();
   METPF_PhotonEnUp_sumEt.clear();
   METPF_PhotonEnDown_sumEt.clear();
   METPF_NoShift_sumEt.clear();
   METPF_METUncertaintySize_sumEt.clear();
   METPF_JetResUpSmear_sumEt.clear();
   METPF_JetResDownSmear_sumEt.clear();
   METPF_METFullUncertaintySize_sumEt.clear();
  //--------------------------------------------------------------
  // MET Puppi without PF
   METPuppiraw_pt.clear();
   METPuppiraw_phi.clear();
   METPuppiraw_sumEt.clear();
   METPuppi_pt.clear();
   METPuppi_px.clear();
   METPuppi_py.clear();
   METPuppi_phi.clear();
   METPuppi_sumEt.clear();
  //-- PT --//
   METPuppi_JetResUp_pt.clear();
   METPuppi_JetResDown_pt.clear();
   METPuppi_JetEnUp_pt.clear();
   METPuppi_JetEnDown_pt.clear();
   METPuppi_MuonEnUp_pt.clear();
   METPuppi_MuonEnDown_pt.clear();
   METPuppi_ElectronEnUp_pt.clear();
   METPuppi_ElectronEnDown_pt.clear();
   METPuppi_TauEnUp_pt.clear();
   METPuppi_TauEnDown_pt.clear();
   METPuppi_UnclusteredEnUp_pt.clear();
   METPuppi_UnclusteredEnDown_pt.clear();
   METPuppi_PhotonEnUp_pt.clear();
   METPuppi_PhotonEnDown_pt.clear();
   METPuppi_NoShift_pt.clear();
   METPuppi_METUncertaintySize_pt.clear();
   METPuppi_JetResUpSmear_pt.clear();
   METPuppi_JetResDownSmear_pt.clear();
   METPuppi_METFullUncertaintySize_pt.clear();
  //-- PX --/
   METPuppi_JetResUp_px.clear();
   METPuppi_JetResDown_px.clear();
   METPuppi_JetEnUp_px.clear();
   METPuppi_JetEnDown_px.clear();
   METPuppi_MuonEnUp_px.clear();
   METPuppi_MuonEnDown_px.clear();
   METPuppi_ElectronEnUp_px.clear();
   METPuppi_ElectronEnDown_px.clear();
   METPuppi_TauEnUp_px.clear();
   METPuppi_TauEnDown_px.clear();
   METPuppi_UnclusteredEnUp_px.clear();
   METPuppi_UnclusteredEnDown_px.clear();
   METPuppi_PhotonEnUp_px.clear();
   METPuppi_PhotonEnDown_px.clear();
   METPuppi_NoShift_px.clear();
   METPuppi_METUncertaintySize_px.clear();
   METPuppi_JetResUpSmear_px.clear();
   METPuppi_JetResDownSmear_px.clear();
   METPuppi_METFullUncertaintySize_px.clear();
  //-- PY --//
   METPuppi_JetResUp_py.clear();
   METPuppi_JetResDown_py.clear();
   METPuppi_JetEnUp_py.clear();
   METPuppi_JetEnDown_py.clear();
   METPuppi_MuonEnUp_py.clear();
   METPuppi_MuonEnDown_py.clear();
   METPuppi_ElectronEnUp_py.clear();
   METPuppi_ElectronEnDown_py.clear();
   METPuppi_TauEnUp_py.clear();
   METPuppi_TauEnDown_py.clear();
   METPuppi_UnclusteredEnUp_py.clear();
   METPuppi_UnclusteredEnDown_py.clear();
   METPuppi_PhotonEnUp_py.clear();
   METPuppi_PhotonEnDown_py.clear();
   METPuppi_NoShift_py.clear();
   METPuppi_METUncertaintySize_py.clear();
   METPuppi_JetResUpSmear_py.clear();
   METPuppi_JetResDownSmear_py.clear();
   METPuppi_METFullUncertaintySize_py.clear();
  //-- PHI --//
   METPuppi_JetResUp_phi.clear();
   METPuppi_JetResDown_phi.clear();
   METPuppi_JetEnUp_phi.clear();
   METPuppi_JetEnDown_phi.clear();
   METPuppi_MuonEnUp_phi.clear();
   METPuppi_MuonEnDown_phi.clear();
   METPuppi_ElectronEnUp_phi.clear();
   METPuppi_ElectronEnDown_phi.clear();
   METPuppi_TauEnUp_phi.clear();
   METPuppi_TauEnDown_phi.clear();
   METPuppi_UnclusteredEnUp_phi.clear();
   METPuppi_UnclusteredEnDown_phi.clear();
   METPuppi_PhotonEnUp_phi.clear();
   METPuppi_PhotonEnDown_phi.clear();
   METPuppi_NoShift_phi.clear();
   METPuppi_METUncertaintySize_phi.clear();
   METPuppi_JetResUpSmear_phi.clear();
   METPuppi_JetResDownSmear_phi.clear();
   METPuppi_METFullUncertaintySize_phi.clear();
  //-- SumEt --//
   METPuppi_JetResUp_sumEt.clear();
   METPuppi_JetResDown_sumEt.clear();
   METPuppi_JetEnUp_sumEt.clear();
   METPuppi_JetEnDown_sumEt.clear();
   METPuppi_MuonEnUp_sumEt.clear();
   METPuppi_MuonEnDown_sumEt.clear();
   METPuppi_ElectronEnUp_sumEt.clear();
   METPuppi_ElectronEnDown_sumEt.clear();
   METPuppi_TauEnUp_sumEt.clear();
   METPuppi_TauEnDown_sumEt.clear();
   METPuppi_UnclusteredEnUp_sumEt.clear();
   METPuppi_UnclusteredEnDown_sumEt.clear();
   METPuppi_PhotonEnUp_sumEt.clear();
   METPuppi_PhotonEnDown_sumEt.clear();
   METPuppi_NoShift_sumEt.clear();
   METPuppi_METUncertaintySize_sumEt.clear();
   METPuppi_JetResUpSmear_sumEt.clear();
   METPuppi_JetResDownSmear_sumEt.clear();
   METPuppi_METFullUncertaintySize_sumEt.clear();
  //------------------------------------------------------------
  // MET Puppi with PF
   METPuppiPFraw_pt.clear();
   METPuppiPFraw_phi.clear();
   METPuppiPFraw_sumEt.clear();
   METPuppiPF_pt.clear();
   METPuppiPF_px.clear();
   METPuppiPF_py.clear();
   METPuppiPF_phi.clear();
   METPuppiPF_sumEt.clear();
  //-- PT --//
   METPuppiPF_JetResUp_pt.clear();
   METPuppiPF_JetResDown_pt.clear();
   METPuppiPF_JetEnUp_pt.clear();
   METPuppiPF_JetEnDown_pt.clear();
   METPuppiPF_MuonEnUp_pt.clear();
   METPuppiPF_MuonEnDown_pt.clear();
   METPuppiPF_ElectronEnUp_pt.clear();
   METPuppiPF_ElectronEnDown_pt.clear();
   METPuppiPF_TauEnUp_pt.clear();
   METPuppiPF_TauEnDown_pt.clear();
   METPuppiPF_UnclusteredEnUp_pt.clear();
   METPuppiPF_UnclusteredEnDown_pt.clear();
   METPuppiPF_PhotonEnUp_pt.clear();
   METPuppiPF_PhotonEnDown_pt.clear();
   METPuppiPF_NoShift_pt.clear();
   METPuppiPF_METUncertaintySize_pt.clear();
   METPuppiPF_JetResUpSmear_pt.clear();
   METPuppiPF_JetResDownSmear_pt.clear();
   METPuppiPF_METFullUncertaintySize_pt.clear();
  //-- PX --/
   METPuppiPF_JetResUp_px.clear();
   METPuppiPF_JetResDown_px.clear();
   METPuppiPF_JetEnUp_px.clear();
   METPuppiPF_JetEnDown_px.clear();
   METPuppiPF_MuonEnUp_px.clear();
   METPuppiPF_MuonEnDown_px.clear();
   METPuppiPF_ElectronEnUp_px.clear();
   METPuppiPF_ElectronEnDown_px.clear();
   METPuppiPF_TauEnUp_px.clear();
   METPuppiPF_TauEnDown_px.clear();
   METPuppiPF_UnclusteredEnUp_px.clear();
   METPuppiPF_UnclusteredEnDown_px.clear();
   METPuppiPF_PhotonEnUp_px.clear();
   METPuppiPF_PhotonEnDown_px.clear();
   METPuppiPF_NoShift_px.clear();
   METPuppiPF_METUncertaintySize_px.clear();
   METPuppiPF_JetResUpSmear_px.clear();
   METPuppiPF_JetResDownSmear_px.clear();
   METPuppiPF_METFullUncertaintySize_px.clear();
  //-- PY --//
   METPuppiPF_JetResUp_py.clear();
   METPuppiPF_JetResDown_py.clear();
   METPuppiPF_JetEnUp_py.clear();
   METPuppiPF_JetEnDown_py.clear();
   METPuppiPF_MuonEnUp_py.clear();
   METPuppiPF_MuonEnDown_py.clear();
   METPuppiPF_ElectronEnUp_py.clear();
   METPuppiPF_ElectronEnDown_py.clear();
   METPuppiPF_TauEnUp_py.clear();
   METPuppiPF_TauEnDown_py.clear();
   METPuppiPF_UnclusteredEnUp_py.clear();
   METPuppiPF_UnclusteredEnDown_py.clear();
   METPuppiPF_PhotonEnUp_py.clear();
   METPuppiPF_PhotonEnDown_py.clear();
   METPuppiPF_NoShift_py.clear();
   METPuppiPF_METUncertaintySize_py.clear();
   METPuppiPF_JetResUpSmear_py.clear();
   METPuppiPF_JetResDownSmear_py.clear();
   METPuppiPF_METFullUncertaintySize_py.clear();
  //-- PHI --//
   METPuppiPF_JetResUp_phi.clear();
   METPuppiPF_JetResDown_phi.clear();
   METPuppiPF_JetEnUp_phi.clear();
   METPuppiPF_JetEnDown_phi.clear();
   METPuppiPF_MuonEnUp_phi.clear();
   METPuppiPF_MuonEnDown_phi.clear();
   METPuppiPF_ElectronEnUp_phi.clear();
   METPuppiPF_ElectronEnDown_phi.clear();
   METPuppiPF_TauEnUp_phi.clear();
   METPuppiPF_TauEnDown_phi.clear();
   METPuppiPF_UnclusteredEnUp_phi.clear();
   METPuppiPF_UnclusteredEnDown_phi.clear();
   METPuppiPF_PhotonEnUp_phi.clear();
   METPuppiPF_PhotonEnDown_phi.clear();
   METPuppiPF_NoShift_phi.clear();
   METPuppiPF_METUncertaintySize_phi.clear();
   METPuppiPF_JetResUpSmear_phi.clear();
   METPuppiPF_JetResDownSmear_phi.clear();
   METPuppiPF_METFullUncertaintySize_phi.clear();
  //-- SumEt --//
   METPuppiPF_JetResUp_sumEt.clear();
   METPuppiPF_JetResDown_sumEt.clear();
   METPuppiPF_JetEnUp_sumEt.clear();
   METPuppiPF_JetEnDown_sumEt.clear();
   METPuppiPF_MuonEnUp_sumEt.clear();
   METPuppiPF_MuonEnDown_sumEt.clear();
   METPuppiPF_ElectronEnUp_sumEt.clear();
   METPuppiPF_ElectronEnDown_sumEt.clear();
   METPuppiPF_TauEnUp_sumEt.clear();
   METPuppiPF_TauEnDown_sumEt.clear();
   METPuppiPF_UnclusteredEnUp_sumEt.clear();
   METPuppiPF_UnclusteredEnDown_sumEt.clear();
   METPuppiPF_PhotonEnUp_sumEt.clear();
   METPuppiPF_PhotonEnDown_sumEt.clear();
   METPuppiPF_NoShift_sumEt.clear();
   METPuppiPF_METUncertaintySize_sumEt.clear();
   METPuppiPF_JetResUpSmear_sumEt.clear();
   METPuppiPF_JetResDownSmear_sumEt.clear();
   METPuppiPF_METFullUncertaintySize_sumEt.clear();

}
